### ISSUE TITLE
Question: Geekdesk Controller

### ISSUE THREAD

**Issue by tommoor** [Hypnopompia/photon-desk#2]
Sorry to file an issue, I couldn't find another way to get in touch with you. I am hoping to build this project and was wondering if you identified the controller that's in use by Geekdesk?

I have an Uplift Desk that also uses an RJ45 connector which appears to be made of off-the-shelf components manufactured by JIECAN. If Geekdesk uses the same supplier (seems likely?!) then I can probably follow your guide.

Thanks in advance, feel free to close this issue.

**Edit:** By the way, if you have any tindie kits left I'd be happy to buy one from you – hmu.

**Comment by Hypnopompia** [comment]
Looking at the uplift desk controller on their website, I'm not sure it's compatible.

The geekdesk controller that I have is the simple Up/Down buttons. It doesn't communicate to the desk controller over any special type of data bus. Just simple on/off buttons. My wifi controller just emulates the button presses.

It looks like the uplift desk is more complicated than that, since it also includes a display for the current height of the desk, which indicates that it's passing more data along the rj45 connection. If you have a logic analyzer tool, you might be able to figure out why type of data bus it is and start from there.
